<?php

declare(strict_types=1);

use Kamelya\Core\Migration;

/**
 * F16.2.9 — Rehberler SEO seed (4 statik rehber × 6 dil = 24 satır).
 *
 * sayfa_kodu = URL path (SeoService::sayfaCoz trim($yol)):
 *   rehberler/bakim | rehberler/malzeme-karsilastirma | rehberler/fark |
 *   rehberler/istanbul-bakim-takvimi
 * SEO bantları: meta_baslik 50–60 byte, meta_aciklama 150–160 byte (UTF-8).
 * canonical dil bazlı; hreflang_json 7 giriş (6 dil + x-default).
 * Idempotent: ON DUPLICATE KEY (sayfa_tipi, sayfa_kodu, dil_kodu).
 * down(): yalnız sayfa_kodu LIKE 'rehberler/%' statik satırları silinir.
 * migrate.php transaction sarmalar — burada beginTransaction YOK.
 */
return new class implements Migration {
    public function up(PDO $baglanti): void
    {
        $ifade = $baglanti->prepare(
            'INSERT INTO seo_verileri
             (sayfa_tipi, referans_id, sayfa_kodu, dil_kodu,
              canonical_url, hreflang_json, meta_baslik, meta_aciklama, robots)
             VALUES ("statik", NULL, ?, ?, ?, ?, ?, ?, "index, follow")
             ON DUPLICATE KEY UPDATE
              canonical_url = VALUES(canonical_url),
              hreflang_json = VALUES(hreflang_json),
              meta_baslik = VALUES(meta_baslik),
              meta_aciklama = VALUES(meta_aciklama),
              robots = VALUES(robots)'
        );

        foreach (self::icerik() as $satir) {
            $ifade->execute($satir);
        }
    }

    public function down(PDO $baglanti): void
    {
        $baglanti->exec('DELETE FROM seo_verileri WHERE sayfa_tipi = "statik" AND sayfa_kodu LIKE "rehberler/%"');
    }

    /**
     * @return array<int, array{0:string,1:string,2:string,3:string,4:string,5:string}>
     */
    private static function icerik(): array
    {
        return [
            ['rehberler/bakim', 'tr', 'https://kamelya.com/rehberler/bakim', '{"tr":"https://kamelya.com/rehberler/bakim","en":"https://kamelya.com/en/rehberler/bakim","de":"https://kamelya.com/de/rehberler/bakim","fr":"https://kamelya.com/fr/rehberler/bakim","it":"https://kamelya.com/it/rehberler/bakim","ar":"https://kamelya.com/ar/rehberler/bakim","x-default":"https://kamelya.com/rehberler/bakim"}', 'Kamelya Bakım Rehberi: Temizlik, Boya, Küf | Kamelya', 'Kamelya bakım rehberi: ilkbahar ve sonbahar yıkama, iki yılda bir boya, küf ve nem kontrolü, alüminyum ve kompozit için düşük bakım adımları.'],
            ['rehberler/bakim', 'en', 'https://kamelya.com/en/rehberler/bakim', '{"tr":"https://kamelya.com/rehberler/bakim","en":"https://kamelya.com/en/rehberler/bakim","de":"https://kamelya.com/de/rehberler/bakim","fr":"https://kamelya.com/fr/rehberler/bakim","it":"https://kamelya.com/it/rehberler/bakim","ar":"https://kamelya.com/ar/rehberler/bakim","x-default":"https://kamelya.com/rehberler/bakim"}', 'Gazebo Care Guide: Seasonal Wash, Paint, Mold | Kamelya', 'Gazebo care guide: spring and autumn washes, paint every two years, mold and moisture checks, plus low-maintenance steps for aluminium and composite builds.'],
            ['rehberler/bakim', 'de', 'https://kamelya.com/de/rehberler/bakim', '{"tr":"https://kamelya.com/rehberler/bakim","en":"https://kamelya.com/en/rehberler/bakim","de":"https://kamelya.com/de/rehberler/bakim","fr":"https://kamelya.com/fr/rehberler/bakim","it":"https://kamelya.com/it/rehberler/bakim","ar":"https://kamelya.com/ar/rehberler/bakim","x-default":"https://kamelya.com/rehberler/bakim"}', 'Kamelya Pflege: Waschen, Lasur, Schimmel | Kamelya', 'Kamelya Pflegeanleitung: Frühjahrs- und Herbstwäsche, Lasur alle zwei Jahre, Schimmel- und Feuchtecheck, Pflegetipps für Aluminium und Verbundstoff.'],
            ['rehberler/bakim', 'fr', 'https://kamelya.com/fr/rehberler/bakim', '{"tr":"https://kamelya.com/rehberler/bakim","en":"https://kamelya.com/en/rehberler/bakim","de":"https://kamelya.com/de/rehberler/bakim","fr":"https://kamelya.com/fr/rehberler/bakim","it":"https://kamelya.com/it/rehberler/bakim","ar":"https://kamelya.com/ar/rehberler/bakim","x-default":"https://kamelya.com/rehberler/bakim"}', 'Guide entretien kamélia : lavage, vernis | Kamelya', 'Guide d’entretien kamélia : lavages de printemps et d’automne, vernis tous les deux ans, contrôle humidité et moisissures, entretien alu et composite.'],
            ['rehberler/bakim', 'it', 'https://kamelya.com/it/rehberler/bakim', '{"tr":"https://kamelya.com/rehberler/bakim","en":"https://kamelya.com/en/rehberler/bakim","de":"https://kamelya.com/de/rehberler/bakim","fr":"https://kamelya.com/fr/rehberler/bakim","it":"https://kamelya.com/it/rehberler/bakim","ar":"https://kamelya.com/ar/rehberler/bakim","x-default":"https://kamelya.com/rehberler/bakim"}', 'Guida manutenzione kamelya: lavaggio, muffa | Kamelya', 'Guida alla manutenzione kamelya: lavaggi primavera e autunno, vernice ogni due anni, controllo umidità e muffa, cura alluminio e composito anche inverno.'],
            ['rehberler/bakim', 'ar', 'https://kamelya.com/ar/rehberler/bakim', '{"tr":"https://kamelya.com/rehberler/bakim","en":"https://kamelya.com/en/rehberler/bakim","de":"https://kamelya.com/de/rehberler/bakim","fr":"https://kamelya.com/fr/rehberler/bakim","it":"https://kamelya.com/it/rehberler/bakim","ar":"https://kamelya.com/ar/rehberler/bakim","x-default":"https://kamelya.com/rehberler/bakim"}', 'دليل صيانة الكاميليا 2026 | Kamelya', 'دليل صيانة الكاميليا: غسيل الربيع والخريف وورنيش كل عامين مع فحص العفن والرطوبة وخطوات.'],
            ['rehberler/malzeme-karsilastirma', 'tr', 'https://kamelya.com/rehberler/malzeme-karsilastirma', '{"tr":"https://kamelya.com/rehberler/malzeme-karsilastirma","en":"https://kamelya.com/en/rehberler/malzeme-karsilastirma","de":"https://kamelya.com/de/rehberler/malzeme-karsilastirma","fr":"https://kamelya.com/fr/rehberler/malzeme-karsilastirma","it":"https://kamelya.com/it/rehberler/malzeme-karsilastirma","ar":"https://kamelya.com/ar/rehberler/malzeme-karsilastirma","x-default":"https://kamelya.com/rehberler/malzeme-karsilastirma"}', 'Ahşap, Alüminyum, Kompozit Malzeme Farkı | Kamelya', 'Ahşap, alüminyum ve kompozit karşılaştırması: bakım sıklığı, dayanım, fiyat çarpanı ve iklim uyumu hangi malzemenin size uyar net gösterir.'],
            ['rehberler/malzeme-karsilastirma', 'en', 'https://kamelya.com/en/rehberler/malzeme-karsilastirma', '{"tr":"https://kamelya.com/rehberler/malzeme-karsilastirma","en":"https://kamelya.com/en/rehberler/malzeme-karsilastirma","de":"https://kamelya.com/de/rehberler/malzeme-karsilastirma","fr":"https://kamelya.com/fr/rehberler/malzeme-karsilastirma","it":"https://kamelya.com/it/rehberler/malzeme-karsilastirma","ar":"https://kamelya.com/ar/rehberler/malzeme-karsilastirma","x-default":"https://kamelya.com/rehberler/malzeme-karsilastirma"}', 'Wood vs Aluminium vs Composite: Material Guide | Kamelya', 'Wood, aluminium and composite comparison: upkeep frequency, durability, price multiplier and climate fit — a clear guide to the right gazebo material.'],
            ['rehberler/malzeme-karsilastirma', 'de', 'https://kamelya.com/de/rehberler/malzeme-karsilastirma', '{"tr":"https://kamelya.com/rehberler/malzeme-karsilastirma","en":"https://kamelya.com/en/rehberler/malzeme-karsilastirma","de":"https://kamelya.com/de/rehberler/malzeme-karsilastirma","fr":"https://kamelya.com/fr/rehberler/malzeme-karsilastirma","it":"https://kamelya.com/it/rehberler/malzeme-karsilastirma","ar":"https://kamelya.com/ar/rehberler/malzeme-karsilastirma","x-default":"https://kamelya.com/rehberler/malzeme-karsilastirma"}', 'Holz, Aluminium, Verbund im Materialvergleich | Kamelya', 'Vergleich Holz, Aluminium und Verbund: Pflegeintervall, Haltbarkeit, Preisfaktor und Klimaeignung — klare Orientierung für das passende Material. Details.'],
            ['rehberler/malzeme-karsilastirma', 'fr', 'https://kamelya.com/fr/rehberler/malzeme-karsilastirma', '{"tr":"https://kamelya.com/rehberler/malzeme-karsilastirma","en":"https://kamelya.com/en/rehberler/malzeme-karsilastirma","de":"https://kamelya.com/de/rehberler/malzeme-karsilastirma","fr":"https://kamelya.com/fr/rehberler/malzeme-karsilastirma","it":"https://kamelya.com/it/rehberler/malzeme-karsilastirma","ar":"https://kamelya.com/ar/rehberler/malzeme-karsilastirma","x-default":"https://kamelya.com/rehberler/malzeme-karsilastirma"}', 'Comparatif matériaux : bois, alu, composite | Kamelya', 'Comparaison bois, aluminium et composite : fréquence d’entretien, durabilité, facteur de prix et adéquation climatique — repère clair pour bien choisir.'],
            ['rehberler/malzeme-karsilastirma', 'it', 'https://kamelya.com/it/rehberler/malzeme-karsilastirma', '{"tr":"https://kamelya.com/rehberler/malzeme-karsilastirma","en":"https://kamelya.com/en/rehberler/malzeme-karsilastirma","de":"https://kamelya.com/de/rehberler/malzeme-karsilastirma","fr":"https://kamelya.com/fr/rehberler/malzeme-karsilastirma","it":"https://kamelya.com/it/rehberler/malzeme-karsilastirma","ar":"https://kamelya.com/ar/rehberler/malzeme-karsilastirma","x-default":"https://kamelya.com/rehberler/malzeme-karsilastirma"}', 'Confronto materiali: legno, alluminio, composito | Kamelya', 'Confronto tra legno, alluminio e composito: frequenza di manutenzione, durabilità, fattore di prezzo e adattamento climatico — guida chiara per scegliere.'],
            ['rehberler/malzeme-karsilastirma', 'ar', 'https://kamelya.com/ar/rehberler/malzeme-karsilastirma', '{"tr":"https://kamelya.com/rehberler/malzeme-karsilastirma","en":"https://kamelya.com/en/rehberler/malzeme-karsilastirma","de":"https://kamelya.com/de/rehberler/malzeme-karsilastirma","fr":"https://kamelya.com/fr/rehberler/malzeme-karsilastirma","it":"https://kamelya.com/it/rehberler/malzeme-karsilastirma","ar":"https://kamelya.com/ar/rehberler/malzeme-karsilastirma","x-default":"https://kamelya.com/rehberler/malzeme-karsilastirma"}', 'مقارنة: خشب وألومنيوم ومركب | Kamelya', 'مقارنة الخشب والألومنيوم والمركّب: تكرار الصيانة والمتانة ومعامل السعر والملاءمة.'],
            ['rehberler/fark', 'tr', 'https://kamelya.com/rehberler/fark', '{"tr":"https://kamelya.com/rehberler/fark","en":"https://kamelya.com/en/rehberler/fark","de":"https://kamelya.com/de/rehberler/fark","fr":"https://kamelya.com/fr/rehberler/fark","it":"https://kamelya.com/it/rehberler/fark","ar":"https://kamelya.com/ar/rehberler/fark","x-default":"https://kamelya.com/rehberler/fark"}', 'Çardak ve Pergola Farkı: Yapı, İzin, Kullanım | Kamelya', 'Çardak ve pergola farkları: yapı tipi, dört mevsim kullanım, yalıtım, ruhsat ihtiyacı ve uygulama alanları tek tabloda net karşılaştırılır.'],
            ['rehberler/fark', 'en', 'https://kamelya.com/en/rehberler/fark', '{"tr":"https://kamelya.com/rehberler/fark","en":"https://kamelya.com/en/rehberler/fark","de":"https://kamelya.com/de/rehberler/fark","fr":"https://kamelya.com/fr/rehberler/fark","it":"https://kamelya.com/it/rehberler/fark","ar":"https://kamelya.com/ar/rehberler/fark","x-default":"https://kamelya.com/rehberler/fark"}', 'Gazebo vs Pergola: Structure, Permit, Everyday Use | Kamelya', 'Gazebo and pergola differences: structure type, four-season use, insulation, permit needs and where each fits — compared in one clear comparison table.'],
            ['rehberler/fark', 'de', 'https://kamelya.com/de/rehberler/fark', '{"tr":"https://kamelya.com/rehberler/fark","en":"https://kamelya.com/en/rehberler/fark","de":"https://kamelya.com/de/rehberler/fark","fr":"https://kamelya.com/fr/rehberler/fark","it":"https://kamelya.com/it/rehberler/fark","ar":"https://kamelya.com/ar/rehberler/fark","x-default":"https://kamelya.com/rehberler/fark"}', 'Pavillon oder Pergola: Aufbau, Genehmigung | Kamelya', 'Unterschied Pavillon und Pergola: Bauart, ganzjährige Nutzung, Isolierung, Genehmigungsbedarf und Einsatzbereiche — klar in einer übersichtlichen Tabelle.'],
            ['rehberler/fark', 'fr', 'https://kamelya.com/fr/rehberler/fark', '{"tr":"https://kamelya.com/rehberler/fark","en":"https://kamelya.com/en/rehberler/fark","de":"https://kamelya.com/de/rehberler/fark","fr":"https://kamelya.com/fr/rehberler/fark","it":"https://kamelya.com/it/rehberler/fark","ar":"https://kamelya.com/ar/rehberler/fark","x-default":"https://kamelya.com/rehberler/fark"}', 'Kiosque ou pergola : structure, permis, usage | Kamelya', 'Différences kiosque et pergola : type de structure, usage quatre saisons, isolation, besoin de permis et usages — comparés en un tableau clair et lisible.'],
            ['rehberler/fark', 'it', 'https://kamelya.com/it/rehberler/fark', '{"tr":"https://kamelya.com/rehberler/fark","en":"https://kamelya.com/en/rehberler/fark","de":"https://kamelya.com/de/rehberler/fark","fr":"https://kamelya.com/fr/rehberler/fark","it":"https://kamelya.com/it/rehberler/fark","ar":"https://kamelya.com/ar/rehberler/fark","x-default":"https://kamelya.com/rehberler/fark"}', 'Gazebo o pergola: struttura, permesso, uso | Kamelya', 'Differenze tra gazebo e pergola: tipo di struttura, uso quattro stagioni, isolamento, necessità di permesso e ambienti — a confronto in tabella chiara.'],
            ['rehberler/fark', 'ar', 'https://kamelya.com/ar/rehberler/fark', '{"tr":"https://kamelya.com/rehberler/fark","en":"https://kamelya.com/en/rehberler/fark","de":"https://kamelya.com/de/rehberler/fark","fr":"https://kamelya.com/fr/rehberler/fark","it":"https://kamelya.com/it/rehberler/fark","ar":"https://kamelya.com/ar/rehberler/fark","x-default":"https://kamelya.com/rehberler/fark"}', 'كوشة أم بيرغولا: الفرق | Kamelya', 'الفرق بين الكوشة والبيرغولا: نوع البناء والاستخدام طوال الفصول والعزل والحاجة للتصريح.'],
            ['rehberler/istanbul-bakim-takvimi', 'tr', 'https://kamelya.com/rehberler/istanbul-bakim-takvimi', '{"tr":"https://kamelya.com/rehberler/istanbul-bakim-takvimi","en":"https://kamelya.com/en/rehberler/istanbul-bakim-takvimi","de":"https://kamelya.com/de/rehberler/istanbul-bakim-takvimi","fr":"https://kamelya.com/fr/rehberler/istanbul-bakim-takvimi","it":"https://kamelya.com/it/rehberler/istanbul-bakim-takvimi","ar":"https://kamelya.com/ar/rehberler/istanbul-bakim-takvimi","x-default":"https://kamelya.com/rehberler/istanbul-bakim-takvimi"}', 'İstanbul Kamelya Bakım Takvimi: 12 Aylık Plan | Kamelya', 'İstanbul iklimine özel 12 aylık kamelya bakım takvimi: kar kontrolü, ilkbahar yıkama, boya penceresi, sonbahar oluk temizliği ve bakım sayacı.'],
            ['rehberler/istanbul-bakim-takvimi', 'en', 'https://kamelya.com/en/rehberler/istanbul-bakim-takvimi', '{"tr":"https://kamelya.com/rehberler/istanbul-bakim-takvimi","en":"https://kamelya.com/en/rehberler/istanbul-bakim-takvimi","de":"https://kamelya.com/de/rehberler/istanbul-bakim-takvimi","fr":"https://kamelya.com/fr/rehberler/istanbul-bakim-takvimi","it":"https://kamelya.com/it/rehberler/istanbul-bakim-takvimi","ar":"https://kamelya.com/ar/rehberler/istanbul-bakim-takvimi","x-default":"https://kamelya.com/rehberler/istanbul-bakim-takvimi"}', 'Istanbul Gazebo Care Calendar: 12-Month Plan | Kamelya', 'A 12-month Istanbul gazebo care calendar shaped by local weather: snow checks, spring wash, paint window, autumn gutter clean and a next-service countdown.'],
            ['rehberler/istanbul-bakim-takvimi', 'de', 'https://kamelya.com/de/rehberler/istanbul-bakim-takvimi', '{"tr":"https://kamelya.com/rehberler/istanbul-bakim-takvimi","en":"https://kamelya.com/en/rehberler/istanbul-bakim-takvimi","de":"https://kamelya.com/de/rehberler/istanbul-bakim-takvimi","fr":"https://kamelya.com/fr/rehberler/istanbul-bakim-takvimi","it":"https://kamelya.com/it/rehberler/istanbul-bakim-takvimi","ar":"https://kamelya.com/ar/rehberler/istanbul-bakim-takvimi","x-default":"https://kamelya.com/rehberler/istanbul-bakim-takvimi"}', 'Istanbul Kamelie Pflegekalender: 12 Monate | Kamelya', '12-Monats-Pflegekalender für Istanbul nach lokalem Klima: Schneekontrolle, Frühjahrswäsche, Lasurfenster, Herbst-Dachrinnenreinigung und Terminanzeige.'],
            ['rehberler/istanbul-bakim-takvimi', 'fr', 'https://kamelya.com/fr/rehberler/istanbul-bakim-takvimi', '{"tr":"https://kamelya.com/rehberler/istanbul-bakim-takvimi","en":"https://kamelya.com/en/rehberler/istanbul-bakim-takvimi","de":"https://kamelya.com/de/rehberler/istanbul-bakim-takvimi","fr":"https://kamelya.com/fr/rehberler/istanbul-bakim-takvimi","it":"https://kamelya.com/it/rehberler/istanbul-bakim-takvimi","ar":"https://kamelya.com/ar/rehberler/istanbul-bakim-takvimi","x-default":"https://kamelya.com/rehberler/istanbul-bakim-takvimi"}', 'Calendrier entretien kamélia Istanbul : 12 mois | Kamelya', 'Calendrier d’entretien sur 12 mois pour Istanbul selon le climat : contrôle neige, lavage printanier, vernis, gouttières d’automne et compte à rebours.'],
            ['rehberler/istanbul-bakim-takvimi', 'it', 'https://kamelya.com/it/rehberler/istanbul-bakim-takvimi', '{"tr":"https://kamelya.com/rehberler/istanbul-bakim-takvimi","en":"https://kamelya.com/en/rehberler/istanbul-bakim-takvimi","de":"https://kamelya.com/de/rehberler/istanbul-bakim-takvimi","fr":"https://kamelya.com/fr/rehberler/istanbul-bakim-takvimi","it":"https://kamelya.com/it/rehberler/istanbul-bakim-takvimi","ar":"https://kamelya.com/ar/rehberler/istanbul-bakim-takvimi","x-default":"https://kamelya.com/rehberler/istanbul-bakim-takvimi"}', 'Calendario manutenzione kamelya Istanbul: 12 mesi | Kamelya', 'Calendario di manutenzione di 12 mesi per Istanbul sul clima locale: controllo neve, lavaggio primaverile, finestra vernice, grondaie e conto alla rovescia.'],
            ['rehberler/istanbul-bakim-takvimi', 'ar', 'https://kamelya.com/ar/rehberler/istanbul-bakim-takvimi', '{"tr":"https://kamelya.com/rehberler/istanbul-bakim-takvimi","en":"https://kamelya.com/en/rehberler/istanbul-bakim-takvimi","de":"https://kamelya.com/de/rehberler/istanbul-bakim-takvimi","fr":"https://kamelya.com/fr/rehberler/istanbul-bakim-takvimi","it":"https://kamelya.com/it/rehberler/istanbul-bakim-takvimi","ar":"https://kamelya.com/ar/rehberler/istanbul-bakim-takvimi","x-default":"https://kamelya.com/rehberler/istanbul-bakim-takvimi"}', 'تقويم صيانة الكاميليا | Kamelya', 'تقويم إسطنبول للكاميليا: فحص الثلج والغسيل والورنيش وتنظيف المزاريب شهرياً لعام 2026.'],
        ];
    }
};
