<?php

declare(strict_types=1);

use Kamelya\Core\Migration;

/**
 * F16.2.5 — Şehir çeviri + SEO seed.
 *
 * 18 sehir_cevirileri (3 şehir × 6 dil) + 36 seo_verileri (2 path × 3 × 6).
 * sayfa_kodu = path-style (SeoService::sayfaCoz trim($yol)):
 *   kamelya-fiyatlari/<slug> | ahsap-kamelya/<slug>
 * SEO bantları: meta_baslik 50–60 byte, meta_aciklama 150–160 byte (UTF-8).
 * canonical dil bazlı + tam path (slug dahil); hreflang_json 7 giriş.
 * Idempotent: ON DUPLICATE KEY (sehir_id,dil_kodu) / (sayfa_tipi,sayfa_kodu,dil_kodu).
 * down(): yalnız sehir path LIKE + sehir_cevirileri (kod IN istanbul/ankara/izmir).
 * migrate.php transaction sarmalar — burada beginTransaction YOK.
 */
return new class implements Migration {
    public function up(PDO $baglanti): void
    {
        $ceviriIfade = $baglanti->prepare(
            'INSERT INTO sehir_cevirileri
             (sehir_id, dil_kodu, seo_baslik, seo_aciklama, icerik, slug)
             VALUES (?, ?, ?, ?, ?, ?)
             ON DUPLICATE KEY UPDATE
              seo_baslik = VALUES(seo_baslik),
              seo_aciklama = VALUES(seo_aciklama),
              icerik = VALUES(icerik),
              slug = VALUES(slug)'
        );

        foreach (self::ceviriler() as $satir) {
            $ceviriIfade->execute($satir);
        }

        $seoIfade = $baglanti->prepare(
            'INSERT INTO seo_verileri
             (sayfa_tipi, referans_id, sayfa_kodu, dil_kodu,
              canonical_url, hreflang_json, meta_baslik, meta_aciklama, anahtar_kelime, robots)
             VALUES ("statik", NULL, ?, ?, ?, ?, ?, ?, ?, "index, follow")
             ON DUPLICATE KEY UPDATE
              canonical_url = VALUES(canonical_url),
              hreflang_json = VALUES(hreflang_json),
              meta_baslik = VALUES(meta_baslik),
              meta_aciklama = VALUES(meta_aciklama),
              anahtar_kelime = VALUES(anahtar_kelime),
              robots = VALUES(robots)'
        );

        foreach (self::seoSatirlari() as $satir) {
            $seoIfade->execute($satir);
        }
    }

    public function down(PDO $baglanti): void
    {
        $baglanti->exec('DELETE FROM seo_verileri WHERE sayfa_tipi = "statik" AND (
            sayfa_kodu LIKE "kamelya-fiyatlari/%" OR sayfa_kodu LIKE "ahsap-kamelya/%")'
        );
        $baglanti->exec('DELETE FROM sehir_cevirileri WHERE sehir_id IN (
            SELECT id FROM (SELECT id FROM sehirler WHERE kod IN ("istanbul","ankara","izmir")) AS s)'
        );
    }

    /**
     * @return array<int, array{0:int,1:string,2:string,3:string,4:string,5:string}>
     */
    private static function ceviriler(): array
    {
        return [
            [1, 'tr', 'İstanbul Kamelya Fiyatları 2026 Ücretsiz Keşif | Kamelya', 'İstanbul kamelya fiyatları 2026: Anadolu ve Avrupa yakası ücretsiz keşif, Bahçelievler Ümraniye Pendik montaj, ölçü sonrası sabit teklif ve yazılı', 'İstanbul genelinde kamelya ve ahşap çardak çözümlerimiz Anadolu yakası ile Avrupa yakası keşiflerini kapsar. Bahçelievler, Ümraniye ve Pendik bölgelerinde montaj ekibimiz ölçü alımından montaja kadar aynı plan üzerinden ilerler; sahil rüzgârı ve nem için ahşap emprenye ile alüminyum çatı seçeneklerini birlikte değerlendiririz. Ücretsiz keşif sonrası net fiyat verilir, teslim ve montaj takvimi yazılı olarak paylaşılır. Site bahçesi, kafe ve özel villa projelerinde ölçüye özel üretim yaparız; oluk ve çatı detayları iklim koşullarına göre yenilenir. Uzun ömür için bakım rehberi ve iki yılda bir boya önerisi sunuyoruz. Teklif aşamasında malzeme, montaj ve nakliye kalemleri ayrı ayrı listelenir, sonradan sürpriz kalem oluşmaz. Ekiplerimiz randevulu çalışır ve keşif genellikle aynı hafta içinde planlanır. Gölge oranı ve yan paneller mevsime göre ayarlanır; bağlantı elemanları korozyona karşı korunur. Montaj günü hava durumu takip edilir ve erteleme olması halinde yeni randevu hemen bildirilir.', 'istanbul'],
            [1, 'en', 'Istanbul Gazebo Prices 2026 | Free Survey | Kamelya', 'Istanbul gazebo prices 2026: free survey on both Bosphorus sides, install near Bahçelievler, Ümraniye and Pendik, fixed quote after measurements with a', 'Our Istanbul gazebo and wood pavilion service covers surveys on both the Anatolian and European sides. Crews in Bahçelievler, Ümraniye and Pendik follow one plan from measure-up to install; we pair timber treatment with aluminium roof options for coastal wind and humidity. A free survey is followed by a fixed quote and a written delivery calendar. Site gardens, cafés and villa plots get made-to-order sizes; gutters and roof details are refreshed for the climate. We include a care guide and a two-year paint window. Quote lines list materials, labour and delivery separately so nothing appears later. Teams work by appointment, usually within the same week as the survey request. Shading ratio and side panels adjust by season; fixings are protected against corrosion. Install-day weather is tracked and a new slot is arranged immediately if postponed.', 'istanbul'],
            [1, 'de', 'Istanbul Pavillon Preise 2026 | Kostenlos | Kamelya', 'Istanbul Pavillon Preise 2026: kostenlose Beratung auf beiden Seiten, Montage Bahçelievler Ümraniye Pendik, Festpreis nach Aufmaß und schriftlicher', 'Unsere Kamelya- und Holz-Pavillon-Lösungen in Istanbul decken Beratungen auf der anatolischen und europäischen Seite ab. Teams in Bahçelievler, Ümraniye und Pendik arbeiten vom Aufmaß bis zur Montage nach einem Plan; für Wind und Feuchte kombinieren wir Holzschutz mit Aluminium-Dächern. Nach der kostenlosen Beratung folgen Festpreis und schriftlicher Terminplan. Wohnanlagen, Cafés und Villengrundstücke erhalten maßgefertigte Maße; Dachdetails werden klimagerecht erneuert. Pflegehinweise und ein Lasurfenster alle zwei Jahre sind enthalten. Material, Montage und Lieferung stehen getrennt im Angebot. Termine meist in derselben Woche wie die Beratung. Beschattung und Seitenwände passen wir der Saison an; Befestigungen sind korrosionsgeschützt. Montagewetter wird verfolgt, bei Verschiebung folgt sofort ein neuer Termin.', 'istanbul'],
            [1, 'fr', 'Prix kamélia Istanbul 2026 | Visite gratuite | Kamelya', 'Prix kamélia Istanbul 2026 : visite gratuite des deux rives, pose près de Bahçelievler Ümraniye Pendik, devis fixe après relevé et plan de pose écrit.', 'Nos kamélias et tonnelles bois pour Istanbul couvrent les visites des rives asiatique et européenne. Les équipes de Bahçelievler, Ümraniye et Pendik suivent un même plan du relevé à la pose ; traitement du bois et toiture aluminium répondent au vent côtier. Visite gratuite, devis ferme et calendrier écrit de livraison. Copropriés, cafés et parcelles de villa reçoivent des dimensions sur mesure ; détails de toiture adaptés au climat. Guide d’entretien et vernis tous les deux ans inclus. Devis sépare matériaux, main-d’œuvre et livraison. Créneaux généralement dans la même semaine que la visite. Ombrage et panneaux latéraux selon la saison ; fixations anticorrosion. Météo de pose suivie, nouveau créneau immédiat en cas d’annulation.', 'istanbul'],
            [1, 'it', 'Istanbul Prezzi gazebo 2026 | Preventivo | Kamelya', 'Prezzi gazebo Istanbul 2026: sopralluogo gratuito su entrambe le sponde, montaggio Bahçelievler Ümraniye Pendik, preventivo fisso e piano di posa scritto.', 'Le nostre soluzioni gazebo e gazebo in legno per Istanbul coprono i sopralluoghi su entrambe le sponde. Le squadre di Bahçelievler, Ümraniye e Pendik seguono un unico piano dal rilievo al montaggio; trattamento del legno e tetto in alluminio per vento e umidità costieri. Sopralluogo gratuito, preventivo fisso e calendario scritto. Condomini, caffè e lotti villa ricevono misure su misura; dettagli di tetto aggiornati per il clima. Guida manutenzione e vernice ogni due anni inclusi. Preventivo separa materiali, manodopera e consegna. Appuntamenti di solito nella stessa settimana del sopralluogo. Ombreggio e pannelli laterali secondo stagione; fissaggi anticorrosione. Meteo di posa monitorato, nuovo slot immediato se rinviato.', 'istanbul'],
            [1, 'ar', 'كاميليا إسطنبول | أسعار 2026 | Kamelya', 'أسعار الكاميليا إسطنبول 2026: معاينة مجانية على الضفتين، تركيب قرب بهچه‌لی‌ار وعمرانيه', 'نقدم حلول الكاميليا والكوش الخشبي في إسطنبول بمعاينات مجانية على ضفتي الأناضول وأوروبا. فرق بهچه‌لی‌ار وعمرانيه وبنديك تتبع خطة واحدة من القياس إلى التركيب، مع معالجة خشب وأسقف ألمنيوم تناسب رياح الساحل والرطوبة. بعد المعاينة يصلك سعر ثابت وجدول تسليم مكتوب. حدائق المجمعات والمقاهي والفلل تحصل على مقاسات مخصّصة، وتفاصيل السقف تُحدَّث حسب المناخ. نرفق دليل صيانة وتذكير بورنيش كل عامين. العرض يفصل المواد واليدوية والنقل حتى لا تظهر بنود لاحقًا. الفرق تعمل بمواعيد غالبًا في نفس أسبوع الطلب. التظليل والألواح الجانبية تتغير مع الموسم، والمسامير محمية من التآكل. يُتابَع طقس يوم التركيب، وعند التأجيل يُحجز موعد جديد فورًا.', 'istanbul'],
            [2, 'tr', 'Ankara Kamelya Fiyatları 2026 | Ostim Üretim | Kamelya', 'Ankara kamelya fiyatları: Ostim üretimi, 30–40 km sabit fiyat çemberi, keşif nakliye montaj aynı teklifte, ölçü sonrası sürpriz kalem yok 2026.', 'Ankara çevresinde üretimimizi Ostim atölyemizden yürütüyoruz. 30–40 km sabit fiyat çemberi içinde keşif, nakliye ve montaj aynı teklife dâhildir; ölçü sonrası sürpriz kalem oluşmaz. Site bahçesi, kafe ve kamu alanları için dayanıklı çatı ve korkuluk seçenekleri önerir, iki yıl garanti ve bakım takvimi ile teslim ederiz. Kışın kar yükü, yazın yüksek güneş için çatı eğimi ve kaplama seçilir; montaj günü hava durumu takip edilir. Belediye ve site yönetimleriyle çalışma prosedürlerimiz nettir. Ölçü ve montaj planı ücretsiz keşif sonrası onaya sunulur. Ahşap emprenye, alüminyum oluk ve çelik bağlantı seçenekleri kullanım senaryosuna göre birlikte değerlendirilir. Teklifte malzeme, işçilik ve nakliye ayrı satırlarda listelenir. Montaj ekibi randevulu çalışır; gecikme durumunda müşteriye aynı gün bilgi verilir. Uzun ömür için iki yılda bir boya ve yılda bir oluk kontrolü öneriyoruz.', 'ankara'],
            [2, 'en', 'Ankara Gazebo Prices 2026 | Free Survey Today | Kamelya', 'Ankara gazebo prices: built in Ostim, fixed pricing within a 30–40 km radius, survey delivery and install in one quote, no surprise lines after measuring.', 'Around Ankara we build in our Ostim workshop. Within a fixed 30–40 km radius the survey, delivery and install share one quote — no surprise lines after measuring. We recommend durable roofs and rails for site gardens, cafés and public spaces, and hand over with a two-year warranty and care calendar. Roof pitch and cladding are chosen for winter snow load and high summer sun; install day weather is tracked. Coordination with site managers and municipalities is straightforward. Measure and install plans are approved after the free survey. Timber treatment, aluminium gutters and steel fixings are chosen together for the use case. Quote lines separate materials, labour and delivery. Crews work by appointment with same-day updates on delays. For long life we suggest paint every two years and a yearly gutter check.', 'ankara'],
            [2, 'de', 'Ankara Pavillon Preise 2026 | Festpreis 40 km | Kamelya', 'Ankara Pavillon Preise: Fertigung Ostim, Festpreis im 30–40-km-Radius, Beratung Lieferung Montage in einem Angebot, kein Aufschlag nach dem Aufmaß.', 'Im Raum Ankara fertigen wir in der Ostim-Werkstatt. Im festen Radius von 30–40 km gehören Beratung, Lieferung und Montage zum selben Angebot — keine Überraschungen nach dem Aufmaß. Für Wohnanlagen, Cafés und öffentliche Flächen empfehlen wir robuste Dächer und Geländer, inklusive zwei Jahre Garantie und Pflegekalender. Dacheindeckung und Neigung richten sich nach Schnee und Sommersonne; Montagewetter wird verfolgt. Abstimmung mit Verwaltungen ist klar. Nach der kostenlosen Beratung folgen Aufmaß- und Montageplan. Holzschutz, Aluminium-Rinnen und Stahlbefestigungen werden passend zum Einsatz gewählt. Angebot trennt Material, Arbeit und Lieferung. Teams arbeiten nach Termin, bei Verzögerung gibt es Info am selben Tag. Für Langlebigkeit empfehlen wir Lasur alle zwei Jahre und jährliche Rinnenkontrolle.', 'ankara'],
            [2, 'fr', 'Prix kamélia Ankara 2026 | Visite gratuite | Kamelya', 'Prix kamélia Ankara : fabrication Ostim, tarif fixe dans un rayon de 30–40 km, visite livraison et pose dans un devis, sans surprise après relevé.', 'Autour de Ankara nous fabriquons à l’atelier Ostim. Dans un rayon fixe de 30–40 km, visite, livraison et pose partagent un devis — sans surprises après le relevé. Toitures et garde-corps durables pour copropriés, cafés et espaces publics, avec garantie deux ans et calendrier d’entretien. Pente et revêtement adaptés à la neige et au soleil d’été ; météo de pose suivie. Coordination avec syndics et mairies claire. Plan de relevé et pose après visite gratuite. Traitement bois, gouttières aluminium et fixations acier selon l’usage. Devis sépare matériaux, pose et livraison. Équipes sur rendez-vous avec info le jour même en cas de retard. Peinture tous les deux ans et contrôle gouttières annuel pour durer.', 'ankara'],
            [2, 'it', 'Ankara Prezzi gazebo 2026 | Listino 40 km | Kamelya', 'Prezzi gazebo Ankara: produzione Ostim, listino fisso entro 30–40 km, sopralluogo consegna e montaggio nello stesso preventivo, nessuna sorpresa dopo rilievo.', 'Nel Ankara produciamo nel laboratorio Ostim. Entro il raggio fisso di 30–40 km, sopralluogo, consegna e montaggio stanno nello stesso preventivo — sorprese dopo il rilievo. Tetti e parapetti resistenti per condomini, caffè e spazi pubblici, con garanzia due anni e calendario manutenzione. Pendenza e copertura per neve inverno e sole estivo; meteo di posa monitorato. Condomìni e comuni: procedura chiara. Piano rilievo e posa dopo sopralluogo gratuito. Trattamento legno, grondaie alluminio e fissaggi acciaio in base all’uso. Preventivo separa materiali, lavoro e consegna. Squadre su appuntamento con aggiornamento entro la stessa giornata. Vernice ogni due anni e controllo grondaie annuale per durare.', 'ankara'],
            [2, 'ar', 'كاميليا أنقرة | أسعار 2026 | Kamelya', 'أسعار الكاميليا أنقرة: إنتاج أوستيم، سعر ثابت ضمن 30–40 كم، معاينة ونقل وتركيب في عرض', 'في محيط أنقرة نُصنّع في ورشة أوستيم. ضمن نطاق ثابت 30–40 كم تشمل نفس العروض المعاينة والنقل والتركيب دون مفاجآت بعد القياس. أسقف وحواجز متينة للمجمعات والمقاهي والفضاءات العامة مع ضمان سنتين وجدول صيانة. ميل السقف والتغطية لحمل الثلج والشمس الصيفية، مع متابعة طقس التركيب. تنسيق واضح مع إدارة المواقع والبلديات. خطة قياس وتركيب بعد المعاينة المجانية. معالجة خشب وألواح ألمنيوم ومسامير حسب الاستخدام. العرض يفصل المواد واليدوية والنقل. الفرق بمواعيد مع إشعار في اليوم نفسه عند التأخير. لعمر طويل نوصي بورنيش كل عامين وفحص المزاريب سنويًا.', 'ankara'],
            [3, 'tr', 'İzmir Kamelya Fiyatları 2026 | Ege İklimi | Kamelya', 'İzmir kamelya fiyatları 2026: Ege iklimine uygun modeller, ücretsiz keşif, Bornova ve çevresinde ölçü montaj planı, net fiyat ve bakım takvimi.', 'İzmir ve çevresinde Ege iklimine uygun kamelya planları yaparız: tuz ve nem için emprenye, güçlü rüzgâr için sabitleme, iki yılda bir boya takvimi. Bornova ve çevre ilçelerde ücretsiz keşif sonrası ölçü ve montaj planı paylaşılır; bakım rehberimizle uzun ömür hedeflenir. Denize yakın bölgelerde metal aksam ve paslanmaz bağlantı önceliklidir. Gölgelik oranı ve yan paneller mevsime göre ayarlanır. Teklifte malzeme, işçilik ve nakliye şeffaf biçimde ayrılır. UV dayanımlı kaplama ve rüzgâr çeperi seçenekleri yaz kış kullanım için önerilir. Montaj öncesi zemin kontrolü yapılır; gerekirse ayarlanabilir ayak veya beton dübel çözümü uygulanır. Bakım rehberi teslimde sunulur, iki yılda bir boya penceresi hatırlatılır. Keşif randevuları genellikle aynı hafta içinde planlanır.', 'izmir'],
            [3, 'en', 'Izmir Gazebo Prices 2026 | Free Site Survey | Kamelya', 'Izmir gazebo prices 2026: models for the Aegean climate, free survey in Bornova and nearby, clear measure-install plan, fixed price and care calendar.', 'In Izmir and the wider Aegean we plan gazebos for the local climate: treatment for salt and humidity, anchoring for strong winds, a paint window every two years. After a free survey in Bornova and nearby districts we share a clear measure and install plan, plus a maintenance guide for a long service life. Coastal plots prioritise corrosion-resistant hardware. Shading ratio and side panels adjust by season. Quotes separate materials, labour and delivery. UV-stable coatings and wind screens are recommended for year-round use. Ground is checked before install; adjustable feet or concrete anchors are used as needed. A care guide is handed over at delivery with a two-year paint reminder. Survey slots are usually offered in the same week.', 'izmir'],
            [3, 'de', 'Izmir Pavillon Preise 2026 | Ägäis Pflege | Kamelya', 'Izmir Pavillon Preise 2026: Modelle für das Ägäis-Klima, kostenlose Beratung in Bornova und Umgebung, klarer Preis, Montageplan und Pflegekalender.', 'In Izmir und der Ägäis planen wir Pavillons nach dem lokalen Klima: Schutz vor Salz und Feuchte, Verankerung bei starkem Wind, Lasurfenster alle zwei Jahre. Nach der kostenlosen Beratung in Bornova und Umgebung folgen Aufmaß-, Montage- und Pflegeplan für lange Lebensdauer. Nahe dem Meer haben korrosionsfeste Beschläge Vorrang. Beschattung und Seitenwände passen wir der Saison an. Angebot trennt Material, Arbeit und Lieferung. UV-beständige Beschichtungen und Windschutz empfehlen wir ganzjährig. Boden wird vor der Montage geprüft; Füße oder Betondübel je nach Bedarf. Pflegehinweis bei Übergabe, Lasur-Erinnerung alle zwei Jahre. Beratungstermine meist in derselben Woche.', 'izmir'],
            [3, 'fr', 'Prix kamélia Izmir 2026 | Visite gratuite | Kamelya', 'Prix kamélia Izmir 2026 : modèles pour le climat égéen, visite gratuite à Bornova, plan relevé-pose clair, tarif net et calendrier d’entretien.', 'à Izmir et dans la mer Égée, nous dimensionnons pour le climat : traitement sel et humidité, ancrage au vent, vernis tous les deux ans. Après la visite gratuite à Bornova et alentours, plan de relevé, pose et entretien pour une longue durée de vie. Près du littoral, quincaillerie anticorrosion prioritaire. Ombrage et panneaux latéraux selon la saison. Devis sépare matériaux, pose et livraison. Revêtements UV et brise-vent recommandés toute l’année. Sol contrôlé avant pose ; pieds réglables ou ancrages béton si besoin. Guide remis à la livraison avec rappel de vernis à deux ans. Visites souvent dans la même semaine.', 'izmir'],
            [3, 'it', 'Prezzi gazebo Izmir 2026 | Preventivo gratuito | Kamelya', 'Prezzi gazebo Izmir 2026: modelli per il clima egeo, sopralluogo gratuito a Bornova, piano rilievo-montaggio chiaro, prezzo netto e calendario manutenzione.', 'A Izmir e nell’Egeo pianifichiamo per il clima: trattamento sale e umidità, ancoraggio al vento, vernice ogni due anni. Dopo il sopralluogo gratuito a Bornova e dintorni, piano rilievo, posa e manutenzione per lunga durata. Vicino al mare priorità a ferramenta anticorrosione. Ombreggio e pannelli laterali secondo stagione. Preventivo separa materiali, lavoro e consegna. Rivestimenti UV e schermi vento consigliati tutto l’anno. Suolo controllato prima della posa; piedini regolabili o tasselli a seconda. Guida consegnata a fine lavori con promemoria vernice biennale. Sopralluoghi spesso nella stessa settimana.', 'izmir'],
            [3, 'ar', 'كاميليا إزمير | أسعار 2026 | Kamelya', 'أسعار الكاميليا إزمير 2026: نماذج لمناخ إيجه، معاينة مجانية في بورنوفا، خطة قياس وتركيب', 'في إزمير وبحر إيجه نخطّط للكاميليا حسب المناخ: معالجة ملح ورطوبة، تثبيت قوي للرياح، وورنيش كل عامين. بعد معاينة مجانية في بورنوفا والمناطق المجاورة نشارك خطة قياس وتركيب وصيانة لعمر طويل. قرب البحر نفضّل تجهيزات مقاومة للتآكل. تظليل وألواح جانبية حسب الموسم. العرض يفصل المواد والتركيب والنقل. طلاء مقاوم للأشعة وحواجز رياح مناسبة طوال السنة. يُفحص الأرض قبل التركيب بأقدار قابلة للضبط أو تثبيت خرساني عند الحاجة. يُسلَّم دليل الصيانة مع تذكير الورنيش بعد سنتين. المواعيد غالبًا في نفس الأسبوع.', 'izmir'],
        ];
    }

    /**
     * @return array<int, array{0:string,1:string,2:string,3:string,4:string,5:string,6:string}>
     */
    private static function seoSatirlari(): array
    {
        return [
            ['kamelya-fiyatlari/istanbul', 'tr', 'https://kamelya.com/kamelya-fiyatlari/istanbul', '{"tr":"https://kamelya.com/kamelya-fiyatlari/istanbul","en":"https://kamelya.com/en/kamelya-fiyatlari/istanbul","de":"https://kamelya.com/de/kamelya-fiyatlari/istanbul","fr":"https://kamelya.com/fr/kamelya-fiyatlari/istanbul","it":"https://kamelya.com/it/kamelya-fiyatlari/istanbul","ar":"https://kamelya.com/ar/kamelya-fiyatlari/istanbul","x-default":"https://kamelya.com/kamelya-fiyatlari/istanbul"}', 'İstanbul Kamelya Fiyatları 2026 Ücretsiz Keşif | Kamelya', 'İstanbul kamelya fiyatları 2026: Anadolu ve Avrupa yakası ücretsiz keşif, Bahçelievler Ümraniye Pendik montaj, ölçü sonrası sabit teklif ve yazılı', 'i̇stanbul kamelya fiyatları, kamelya fiyatları 2026, ücretsiz keşif, i̇stanbul çardak'],
            ['ahsap-kamelya/istanbul', 'tr', 'https://kamelya.com/ahsap-kamelya/istanbul', '{"tr":"https://kamelya.com/ahsap-kamelya/istanbul","en":"https://kamelya.com/en/ahsap-kamelya/istanbul","de":"https://kamelya.com/de/ahsap-kamelya/istanbul","fr":"https://kamelya.com/fr/ahsap-kamelya/istanbul","it":"https://kamelya.com/it/ahsap-kamelya/istanbul","ar":"https://kamelya.com/ar/ahsap-kamelya/istanbul","x-default":"https://kamelya.com/ahsap-kamelya/istanbul"}', 'İstanbul Ahşap Kamelya 2026 | Yerel Montaj | Kamelya', 'İstanbul ahşap kamelya modelleri: dayanıklı çatı, yerel montaj ekibi, Bahçelievler Ümraniye Pendik hızlı teslim, ölçüye özel üretim ve garanti', 'i̇stanbul ahşap kamelya, ahşap kamelya modelleri, ücretsiz keşif, i̇stanbul çardak'],
            ['kamelya-fiyatlari/istanbul', 'en', 'https://kamelya.com/en/kamelya-fiyatlari/istanbul', '{"tr":"https://kamelya.com/kamelya-fiyatlari/istanbul","en":"https://kamelya.com/en/kamelya-fiyatlari/istanbul","de":"https://kamelya.com/de/kamelya-fiyatlari/istanbul","fr":"https://kamelya.com/fr/kamelya-fiyatlari/istanbul","it":"https://kamelya.com/it/kamelya-fiyatlari/istanbul","ar":"https://kamelya.com/ar/kamelya-fiyatlari/istanbul","x-default":"https://kamelya.com/kamelya-fiyatlari/istanbul"}', 'Istanbul Gazebo Prices 2026 | Free Survey | Kamelya', 'Istanbul gazebo prices 2026: free survey on both Bosphorus sides, install near Bahçelievler, Ümraniye and Pendik, fixed quote after measurements with a', 'Istanbul gazebo prices, gazebo prices 2026, free survey, Istanbul pavilion'],
            ['ahsap-kamelya/istanbul', 'en', 'https://kamelya.com/en/ahsap-kamelya/istanbul', '{"tr":"https://kamelya.com/ahsap-kamelya/istanbul","en":"https://kamelya.com/en/ahsap-kamelya/istanbul","de":"https://kamelya.com/de/ahsap-kamelya/istanbul","fr":"https://kamelya.com/fr/ahsap-kamelya/istanbul","it":"https://kamelya.com/it/ahsap-kamelya/istanbul","ar":"https://kamelya.com/ar/ahsap-kamelya/istanbul","x-default":"https://kamelya.com/ahsap-kamelya/istanbul"}', 'Istanbul Wood Gazebo 2026 | Local Install | Kamelya', 'Istanbul wood gazebo models: durable roofs, local install crews, quick delivery to Bahçelievler Ümraniye Pendik, made-to-order sizes and warranty included', 'Istanbul wood gazebo, wood gazebo models, free survey, Istanbul pavilion'],
            ['kamelya-fiyatlari/istanbul', 'de', 'https://kamelya.com/de/kamelya-fiyatlari/istanbul', '{"tr":"https://kamelya.com/kamelya-fiyatlari/istanbul","en":"https://kamelya.com/en/kamelya-fiyatlari/istanbul","de":"https://kamelya.com/de/kamelya-fiyatlari/istanbul","fr":"https://kamelya.com/fr/kamelya-fiyatlari/istanbul","it":"https://kamelya.com/it/kamelya-fiyatlari/istanbul","ar":"https://kamelya.com/ar/kamelya-fiyatlari/istanbul","x-default":"https://kamelya.com/kamelya-fiyatlari/istanbul"}', 'Istanbul Pavillon Preise 2026 | Kostenlos | Kamelya', 'Istanbul Pavillon Preise 2026: kostenlose Beratung auf beiden Seiten, Montage Bahçelievler Ümraniye Pendik, Festpreis nach Aufmaß und schriftlicher', 'Istanbul Pavillon Preise, Pavillon Preise 2026, kostenlose Beratung, Istanbul Gartenpavillon'],
            ['ahsap-kamelya/istanbul', 'de', 'https://kamelya.com/de/ahsap-kamelya/istanbul', '{"tr":"https://kamelya.com/ahsap-kamelya/istanbul","en":"https://kamelya.com/en/ahsap-kamelya/istanbul","de":"https://kamelya.com/de/ahsap-kamelya/istanbul","fr":"https://kamelya.com/fr/ahsap-kamelya/istanbul","it":"https://kamelya.com/it/ahsap-kamelya/istanbul","ar":"https://kamelya.com/ar/ahsap-kamelya/istanbul","x-default":"https://kamelya.com/ahsap-kamelya/istanbul"}', 'Istanbul Holz-Pavillon 2026 | Maßanfertigung | Kamelya', 'Istanbul Holz-Pavillon Modelle: langlebige Dächer, lokale Montageteams, schnelle Lieferung nach Bahçelievler Ümraniye Pendik, Massanfertigung und Garantie.', 'Istanbul Holz-Pavillon, Holz-Pavillon Modelle, kostenlose Beratung, Istanbul Gartenpavillon'],
            ['kamelya-fiyatlari/istanbul', 'fr', 'https://kamelya.com/fr/kamelya-fiyatlari/istanbul', '{"tr":"https://kamelya.com/kamelya-fiyatlari/istanbul","en":"https://kamelya.com/en/kamelya-fiyatlari/istanbul","de":"https://kamelya.com/de/kamelya-fiyatlari/istanbul","fr":"https://kamelya.com/fr/kamelya-fiyatlari/istanbul","it":"https://kamelya.com/it/kamelya-fiyatlari/istanbul","ar":"https://kamelya.com/ar/kamelya-fiyatlari/istanbul","x-default":"https://kamelya.com/kamelya-fiyatlari/istanbul"}', 'Prix kamélia Istanbul 2026 | Visite gratuite | Kamelya', 'Prix kamélia Istanbul 2026 : visite gratuite des deux rives, pose près de Bahçelievler Ümraniye Pendik, devis fixe après relevé et plan de pose écrit.', 'prix kamélia Istanbul, prix kamélia 2026, visite gratuite, tonnelle Istanbul'],
            ['ahsap-kamelya/istanbul', 'fr', 'https://kamelya.com/fr/ahsap-kamelya/istanbul', '{"tr":"https://kamelya.com/ahsap-kamelya/istanbul","en":"https://kamelya.com/en/ahsap-kamelya/istanbul","de":"https://kamelya.com/de/ahsap-kamelya/istanbul","fr":"https://kamelya.com/fr/ahsap-kamelya/istanbul","it":"https://kamelya.com/it/ahsap-kamelya/istanbul","ar":"https://kamelya.com/ar/ahsap-kamelya/istanbul","x-default":"https://kamelya.com/ahsap-kamelya/istanbul"}', 'Istanbul Kamélia bois 2026 | Pose locale | Kamelya', 'Modèles kamélia bois Istanbul : toitures durables, équipes locales, livraison rapide vers Bahçelievler Ümraniye Pendik, dimensions sur mesure et garantie.', 'kamélia bois Istanbul, kamélia bois modèle, visite gratuite, tonnelle Istanbul'],
            ['kamelya-fiyatlari/istanbul', 'it', 'https://kamelya.com/it/kamelya-fiyatlari/istanbul', '{"tr":"https://kamelya.com/kamelya-fiyatlari/istanbul","en":"https://kamelya.com/en/kamelya-fiyatlari/istanbul","de":"https://kamelya.com/de/kamelya-fiyatlari/istanbul","fr":"https://kamelya.com/fr/kamelya-fiyatlari/istanbul","it":"https://kamelya.com/it/kamelya-fiyatlari/istanbul","ar":"https://kamelya.com/ar/kamelya-fiyatlari/istanbul","x-default":"https://kamelya.com/kamelya-fiyatlari/istanbul"}', 'Istanbul Prezzi gazebo 2026 | Preventivo | Kamelya', 'Prezzi gazebo Istanbul 2026: sopralluogo gratuito su entrambe le sponde, montaggio Bahçelievler Ümraniye Pendik, preventivo fisso e piano di posa scritto.', 'prezzi gazebo Istanbul, prezzi gazebo 2026, sopralluogo gratuito, pensilina Istanbul'],
            ['ahsap-kamelya/istanbul', 'it', 'https://kamelya.com/it/ahsap-kamelya/istanbul', '{"tr":"https://kamelya.com/ahsap-kamelya/istanbul","en":"https://kamelya.com/en/ahsap-kamelya/istanbul","de":"https://kamelya.com/de/ahsap-kamelya/istanbul","fr":"https://kamelya.com/fr/ahsap-kamelya/istanbul","it":"https://kamelya.com/it/ahsap-kamelya/istanbul","ar":"https://kamelya.com/ar/ahsap-kamelya/istanbul","x-default":"https://kamelya.com/ahsap-kamelya/istanbul"}', 'Gazebo legno Istanbul 2026 | Sopralluogo | Kamelya', 'Modelli gazebo legno Istanbul: tetti resistenti, squadre locali, consegna rapida a Bahçelievler Ümraniye Pendik, misure su misura e garanzia due anni.', 'gazebo legno Istanbul, gazebo legno modelli, sopralluogo gratuito, pensilina Istanbul'],
            ['kamelya-fiyatlari/istanbul', 'ar', 'https://kamelya.com/ar/kamelya-fiyatlari/istanbul', '{"tr":"https://kamelya.com/kamelya-fiyatlari/istanbul","en":"https://kamelya.com/en/kamelya-fiyatlari/istanbul","de":"https://kamelya.com/de/kamelya-fiyatlari/istanbul","fr":"https://kamelya.com/fr/kamelya-fiyatlari/istanbul","it":"https://kamelya.com/it/kamelya-fiyatlari/istanbul","ar":"https://kamelya.com/ar/kamelya-fiyatlari/istanbul","x-default":"https://kamelya.com/kamelya-fiyatlari/istanbul"}', 'كاميليا إسطنبول | أسعار 2026 | Kamelya', 'أسعار الكاميليا إسطنبول 2026: معاينة مجانية على الضفتين، تركيب قرب بهچه‌لی‌ار وعمرانيه', 'أسعار الكاميليا إسطنبول, أسعار كاميليا 2026, معاينة مجانية, كوش إسطنبول'],
            ['ahsap-kamelya/istanbul', 'ar', 'https://kamelya.com/ar/ahsap-kamelya/istanbul', '{"tr":"https://kamelya.com/ahsap-kamelya/istanbul","en":"https://kamelya.com/en/ahsap-kamelya/istanbul","de":"https://kamelya.com/de/ahsap-kamelya/istanbul","fr":"https://kamelya.com/fr/ahsap-kamelya/istanbul","it":"https://kamelya.com/it/ahsap-kamelya/istanbul","ar":"https://kamelya.com/ar/ahsap-kamelya/istanbul","x-default":"https://kamelya.com/ahsap-kamelya/istanbul"}', 'كوش خشبي إسطنبول 2026 | تركيب | Kamelya', 'نماذج كوش خشبي إسطنبول: أسقف متينة، فرق تركيب محلية، تسليم سريع لبهچه‌لی‌ار وعمرانيه', 'كوش خشبي إسطنبول, نماذج كوش خشبي, معاينة مجانية, كوش إسطنبول'],
            ['kamelya-fiyatlari/ankara', 'tr', 'https://kamelya.com/kamelya-fiyatlari/ankara', '{"tr":"https://kamelya.com/kamelya-fiyatlari/ankara","en":"https://kamelya.com/en/kamelya-fiyatlari/ankara","de":"https://kamelya.com/de/kamelya-fiyatlari/ankara","fr":"https://kamelya.com/fr/kamelya-fiyatlari/ankara","it":"https://kamelya.com/it/kamelya-fiyatlari/ankara","ar":"https://kamelya.com/ar/kamelya-fiyatlari/ankara","x-default":"https://kamelya.com/kamelya-fiyatlari/ankara"}', 'Ankara Kamelya Fiyatları 2026 | Ostim Üretim | Kamelya', 'Ankara kamelya fiyatları: Ostim üretimi, 30–40 km sabit fiyat çemberi, keşif nakliye montaj aynı teklifte, ölçü sonrası sürpriz kalem yok 2026.', 'ankara kamelya fiyatları, kamelya fiyatları 2026, ücretsiz keşif, ankara çardak'],
            ['ahsap-kamelya/ankara', 'tr', 'https://kamelya.com/ahsap-kamelya/ankara', '{"tr":"https://kamelya.com/ahsap-kamelya/ankara","en":"https://kamelya.com/en/ahsap-kamelya/ankara","de":"https://kamelya.com/de/ahsap-kamelya/ankara","fr":"https://kamelya.com/fr/ahsap-kamelya/ankara","it":"https://kamelya.com/it/ahsap-kamelya/ankara","ar":"https://kamelya.com/ar/ahsap-kamelya/ankara","x-default":"https://kamelya.com/ahsap-kamelya/ankara"}', 'Ankara Ahşap Kamelya 2026 | Ostim Üretim | Kamelya', 'Ankara ahşap kamelya: Ostim atölyesinde üretim, 30–40 km montaj, ölçüm sonrası sabit fiyat, iki yıl garanti ve bakım takvimi ile teslim 2026.', 'ankara ahşap kamelya, ahşap kamelya modelleri, ücretsiz keşif, ankara çardak'],
            ['kamelya-fiyatlari/ankara', 'en', 'https://kamelya.com/en/kamelya-fiyatlari/ankara', '{"tr":"https://kamelya.com/kamelya-fiyatlari/ankara","en":"https://kamelya.com/en/kamelya-fiyatlari/ankara","de":"https://kamelya.com/de/kamelya-fiyatlari/ankara","fr":"https://kamelya.com/fr/kamelya-fiyatlari/ankara","it":"https://kamelya.com/it/kamelya-fiyatlari/ankara","ar":"https://kamelya.com/ar/kamelya-fiyatlari/ankara","x-default":"https://kamelya.com/kamelya-fiyatlari/ankara"}', 'Ankara Gazebo Prices 2026 | Free Survey Today | Kamelya', 'Ankara gazebo prices: built in Ostim, fixed pricing within a 30–40 km radius, survey delivery and install in one quote, no surprise lines after measuring.', 'Ankara gazebo prices, gazebo prices 2026, free survey, Ankara pavilion'],
            ['ahsap-kamelya/ankara', 'en', 'https://kamelya.com/en/ahsap-kamelya/ankara', '{"tr":"https://kamelya.com/ahsap-kamelya/ankara","en":"https://kamelya.com/en/ahsap-kamelya/ankara","de":"https://kamelya.com/de/ahsap-kamelya/ankara","fr":"https://kamelya.com/fr/ahsap-kamelya/ankara","it":"https://kamelya.com/it/ahsap-kamelya/ankara","ar":"https://kamelya.com/ar/ahsap-kamelya/ankara","x-default":"https://kamelya.com/ahsap-kamelya/ankara"}', 'Ankara Wood Gazebo 2026 | Local Install Crew | Kamelya', 'Ankara wood gazebo: built in the Ostim workshop, install within 30–40 km, fixed price after survey, two-year warranty and a care calendar included free.', 'Ankara wood gazebo, wood gazebo models, free survey, Ankara pavilion'],
            ['kamelya-fiyatlari/ankara', 'de', 'https://kamelya.com/de/kamelya-fiyatlari/ankara', '{"tr":"https://kamelya.com/kamelya-fiyatlari/ankara","en":"https://kamelya.com/en/kamelya-fiyatlari/ankara","de":"https://kamelya.com/de/kamelya-fiyatlari/ankara","fr":"https://kamelya.com/fr/kamelya-fiyatlari/ankara","it":"https://kamelya.com/it/kamelya-fiyatlari/ankara","ar":"https://kamelya.com/ar/kamelya-fiyatlari/ankara","x-default":"https://kamelya.com/kamelya-fiyatlari/ankara"}', 'Ankara Pavillon Preise 2026 | Festpreis 40 km | Kamelya', 'Ankara Pavillon Preise: Fertigung Ostim, Festpreis im 30–40-km-Radius, Beratung Lieferung Montage in einem Angebot, kein Aufschlag nach dem Aufmaß.', 'Ankara Pavillon Preise, Pavillon Preise 2026, kostenlose Beratung, Ankara Gartenpavillon'],
            ['ahsap-kamelya/ankara', 'de', 'https://kamelya.com/de/ahsap-kamelya/ankara', '{"tr":"https://kamelya.com/ahsap-kamelya/ankara","en":"https://kamelya.com/en/ahsap-kamelya/ankara","de":"https://kamelya.com/de/ahsap-kamelya/ankara","fr":"https://kamelya.com/fr/ahsap-kamelya/ankara","it":"https://kamelya.com/it/ahsap-kamelya/ankara","ar":"https://kamelya.com/ar/ahsap-kamelya/ankara","x-default":"https://kamelya.com/ahsap-kamelya/ankara"}', 'Ankara Holz-Pavillon 2026 | Ostim Fertigung | Kamelya', 'Ankara Holz-Pavillon: Fertigung Ostim-Werkstatt, Montage 30–40 km, Festpreis nach Aufmaß, zwei Jahre Garantie und Pflegekalender für lange Nutzung.', 'Ankara Holz-Pavillon, Holz-Pavillon Modelle, kostenlose Beratung, Ankara Gartenpavillon'],
            ['kamelya-fiyatlari/ankara', 'fr', 'https://kamelya.com/fr/kamelya-fiyatlari/ankara', '{"tr":"https://kamelya.com/kamelya-fiyatlari/ankara","en":"https://kamelya.com/en/kamelya-fiyatlari/ankara","de":"https://kamelya.com/de/kamelya-fiyatlari/ankara","fr":"https://kamelya.com/fr/kamelya-fiyatlari/ankara","it":"https://kamelya.com/it/kamelya-fiyatlari/ankara","ar":"https://kamelya.com/ar/kamelya-fiyatlari/ankara","x-default":"https://kamelya.com/kamelya-fiyatlari/ankara"}', 'Prix kamélia Ankara 2026 | Visite gratuite | Kamelya', 'Prix kamélia Ankara : fabrication Ostim, tarif fixe dans un rayon de 30–40 km, visite livraison et pose dans un devis, sans surprise après relevé.', 'prix kamélia Ankara, prix kamélia 2026, visite gratuite, tonnelle Ankara'],
            ['ahsap-kamelya/ankara', 'fr', 'https://kamelya.com/fr/ahsap-kamelya/ankara', '{"tr":"https://kamelya.com/ahsap-kamelya/ankara","en":"https://kamelya.com/en/ahsap-kamelya/ankara","de":"https://kamelya.com/de/ahsap-kamelya/ankara","fr":"https://kamelya.com/fr/ahsap-kamelya/ankara","it":"https://kamelya.com/it/ahsap-kamelya/ankara","ar":"https://kamelya.com/ar/ahsap-kamelya/ankara","x-default":"https://kamelya.com/ahsap-kamelya/ankara"}', 'Ankara Kamélia bois 2026 | Atelier Ostim | Kamelya', 'Ankara kamélia bois : atelier Ostim, pose dans un rayon de 30–40 km, prix fixe après visite, garantie deux ans et calendrier d’entretien clair et simple.', 'kamélia bois Ankara, kamélia bois modèle, visite gratuite, tonnelle Ankara'],
            ['kamelya-fiyatlari/ankara', 'it', 'https://kamelya.com/it/kamelya-fiyatlari/ankara', '{"tr":"https://kamelya.com/kamelya-fiyatlari/ankara","en":"https://kamelya.com/en/kamelya-fiyatlari/ankara","de":"https://kamelya.com/de/kamelya-fiyatlari/ankara","fr":"https://kamelya.com/fr/kamelya-fiyatlari/ankara","it":"https://kamelya.com/it/kamelya-fiyatlari/ankara","ar":"https://kamelya.com/ar/kamelya-fiyatlari/ankara","x-default":"https://kamelya.com/kamelya-fiyatlari/ankara"}', 'Ankara Prezzi gazebo 2026 | Listino 40 km | Kamelya', 'Prezzi gazebo Ankara: produzione Ostim, listino fisso entro 30–40 km, sopralluogo consegna e montaggio nello stesso preventivo, nessuna sorpresa dopo rilievo.', 'prezzi gazebo Ankara, prezzi gazebo 2026, sopralluogo gratuito, pensilina Ankara'],
            ['ahsap-kamelya/ankara', 'it', 'https://kamelya.com/it/ahsap-kamelya/ankara', '{"tr":"https://kamelya.com/ahsap-kamelya/ankara","en":"https://kamelya.com/en/ahsap-kamelya/ankara","de":"https://kamelya.com/de/ahsap-kamelya/ankara","fr":"https://kamelya.com/fr/ahsap-kamelya/ankara","it":"https://kamelya.com/it/ahsap-kamelya/ankara","ar":"https://kamelya.com/ar/ahsap-kamelya/ankara","x-default":"https://kamelya.com/ahsap-kamelya/ankara"}', 'Ankara Gazebo legno 2026 | Officina Ostim | Kamelya', 'Ankara gazebo legno: realizzato a Ostim, montaggio entro 30–40 km, prezzo fisso dopo sopralluogo, garanzia due anni e calendario manutenzione. Elenco chiaro.', 'gazebo legno Ankara, gazebo legno modelli, sopralluogo gratuito, pensilina Ankara'],
            ['kamelya-fiyatlari/ankara', 'ar', 'https://kamelya.com/ar/kamelya-fiyatlari/ankara', '{"tr":"https://kamelya.com/kamelya-fiyatlari/ankara","en":"https://kamelya.com/en/kamelya-fiyatlari/ankara","de":"https://kamelya.com/de/kamelya-fiyatlari/ankara","fr":"https://kamelya.com/fr/kamelya-fiyatlari/ankara","it":"https://kamelya.com/it/kamelya-fiyatlari/ankara","ar":"https://kamelya.com/ar/kamelya-fiyatlari/ankara","x-default":"https://kamelya.com/kamelya-fiyatlari/ankara"}', 'كاميليا أنقرة | أسعار 2026 | Kamelya', 'أسعار الكاميليا أنقرة: إنتاج أوستيم، سعر ثابت ضمن 30–40 كم، معاينة ونقل وتركيب في عرض', 'أسعار الكاميليا أنقرة, أسعار كاميليا 2026, معاينة مجانية, كوش أنقرة'],
            ['ahsap-kamelya/ankara', 'ar', 'https://kamelya.com/ar/ahsap-kamelya/ankara', '{"tr":"https://kamelya.com/ahsap-kamelya/ankara","en":"https://kamelya.com/en/ahsap-kamelya/ankara","de":"https://kamelya.com/de/ahsap-kamelya/ankara","fr":"https://kamelya.com/fr/ahsap-kamelya/ankara","it":"https://kamelya.com/it/ahsap-kamelya/ankara","ar":"https://kamelya.com/ar/ahsap-kamelya/ankara","x-default":"https://kamelya.com/ahsap-kamelya/ankara"}', 'كوش خشبي أنقرة 2026 | أوستيم | Kamelya', 'الكوش الخشبي أنقرة: صناعة أوستيم، تركيب خلال 30–40 كم، سعر ثابت بعد المعاينة، ضمان سنتين', 'كوش خشبي أنقرة, نماذج كوش خشبي, معاينة مجانية, كوش أنقرة'],
            ['kamelya-fiyatlari/izmir', 'tr', 'https://kamelya.com/kamelya-fiyatlari/izmir', '{"tr":"https://kamelya.com/kamelya-fiyatlari/izmir","en":"https://kamelya.com/en/kamelya-fiyatlari/izmir","de":"https://kamelya.com/de/kamelya-fiyatlari/izmir","fr":"https://kamelya.com/fr/kamelya-fiyatlari/izmir","it":"https://kamelya.com/it/kamelya-fiyatlari/izmir","ar":"https://kamelya.com/ar/kamelya-fiyatlari/izmir","x-default":"https://kamelya.com/kamelya-fiyatlari/izmir"}', 'İzmir Kamelya Fiyatları 2026 | Ege İklimi | Kamelya', 'İzmir kamelya fiyatları 2026: Ege iklimine uygun modeller, ücretsiz keşif, Bornova ve çevresinde ölçü montaj planı, net fiyat ve bakım takvimi.', 'i̇zmir kamelya fiyatları, kamelya fiyatları 2026, ücretsiz keşif, i̇zmir çardak'],
            ['ahsap-kamelya/izmir', 'tr', 'https://kamelya.com/ahsap-kamelya/izmir', '{"tr":"https://kamelya.com/ahsap-kamelya/izmir","en":"https://kamelya.com/en/ahsap-kamelya/izmir","de":"https://kamelya.com/de/ahsap-kamelya/izmir","fr":"https://kamelya.com/fr/ahsap-kamelya/izmir","it":"https://kamelya.com/it/ahsap-kamelya/izmir","ar":"https://kamelya.com/ar/ahsap-kamelya/izmir","x-default":"https://kamelya.com/ahsap-kamelya/izmir"}', 'İzmir Ahşap Kamelya 2026 | Ege İklimi | Kamelya', 'İzmir ahşap kamelya: Ege iklimine uygun emprenye, iki yılda bir boya, ücretsiz keşif, Bornova çevresinde montaj planı ve garanti ile teslim 2026.', 'i̇zmir ahşap kamelya, ahşap kamelya modelleri, ücretsiz keşif, i̇zmir çardak'],
            ['kamelya-fiyatlari/izmir', 'en', 'https://kamelya.com/en/kamelya-fiyatlari/izmir', '{"tr":"https://kamelya.com/kamelya-fiyatlari/izmir","en":"https://kamelya.com/en/kamelya-fiyatlari/izmir","de":"https://kamelya.com/de/kamelya-fiyatlari/izmir","fr":"https://kamelya.com/fr/kamelya-fiyatlari/izmir","it":"https://kamelya.com/it/kamelya-fiyatlari/izmir","ar":"https://kamelya.com/ar/kamelya-fiyatlari/izmir","x-default":"https://kamelya.com/kamelya-fiyatlari/izmir"}', 'Izmir Gazebo Prices 2026 | Free Site Survey | Kamelya', 'Izmir gazebo prices 2026: models for the Aegean climate, free survey in Bornova and nearby, clear measure-install plan, fixed price and care calendar.', 'Izmir gazebo prices, gazebo prices 2026, free survey, Izmir pavilion'],
            ['ahsap-kamelya/izmir', 'en', 'https://kamelya.com/en/ahsap-kamelya/izmir', '{"tr":"https://kamelya.com/ahsap-kamelya/izmir","en":"https://kamelya.com/en/ahsap-kamelya/izmir","de":"https://kamelya.com/de/ahsap-kamelya/izmir","fr":"https://kamelya.com/fr/ahsap-kamelya/izmir","it":"https://kamelya.com/it/ahsap-kamelya/izmir","ar":"https://kamelya.com/ar/ahsap-kamelya/izmir","x-default":"https://kamelya.com/ahsap-kamelya/izmir"}', 'Izmir Wood Gazebo 2026 | Local Install Crew | Kamelya', 'Izmir wood gazebo: Aegean-ready treatment, paint every two years, free survey, install plan around Bornova and a two-year warranty with care guide. Clear list.', 'Izmir wood gazebo, wood gazebo models, free survey, Izmir pavilion'],
            ['kamelya-fiyatlari/izmir', 'de', 'https://kamelya.com/de/kamelya-fiyatlari/izmir', '{"tr":"https://kamelya.com/kamelya-fiyatlari/izmir","en":"https://kamelya.com/en/kamelya-fiyatlari/izmir","de":"https://kamelya.com/de/kamelya-fiyatlari/izmir","fr":"https://kamelya.com/fr/kamelya-fiyatlari/izmir","it":"https://kamelya.com/it/kamelya-fiyatlari/izmir","ar":"https://kamelya.com/ar/kamelya-fiyatlari/izmir","x-default":"https://kamelya.com/kamelya-fiyatlari/izmir"}', 'Izmir Pavillon Preise 2026 | Ägäis Pflege | Kamelya', 'Izmir Pavillon Preise 2026: Modelle für das Ägäis-Klima, kostenlose Beratung in Bornova und Umgebung, klarer Preis, Montageplan und Pflegekalender.', 'Izmir Pavillon Preise, Pavillon Preise 2026, kostenlose Beratung, Izmir Gartenpavillon'],
            ['ahsap-kamelya/izmir', 'de', 'https://kamelya.com/de/ahsap-kamelya/izmir', '{"tr":"https://kamelya.com/ahsap-kamelya/izmir","en":"https://kamelya.com/en/ahsap-kamelya/izmir","de":"https://kamelya.com/de/ahsap-kamelya/izmir","fr":"https://kamelya.com/fr/ahsap-kamelya/izmir","it":"https://kamelya.com/it/ahsap-kamelya/izmir","ar":"https://kamelya.com/ar/ahsap-kamelya/izmir","x-default":"https://kamelya.com/ahsap-kamelya/izmir"}', 'Izmir Holz-Pavillon 2026 | Ägäis Klima | Kamelya', 'Izmir Holz-Pavillon: Pflege für das Ägäis-Klima, Lack alle zwei Jahre, kostenlose Beratung, Montageplan Bornova und zwei Jahre Garantie inklusive + Pflege.', 'Izmir Holz-Pavillon, Holz-Pavillon Modelle, kostenlose Beratung, Izmir Gartenpavillon'],
            ['kamelya-fiyatlari/izmir', 'fr', 'https://kamelya.com/fr/kamelya-fiyatlari/izmir', '{"tr":"https://kamelya.com/kamelya-fiyatlari/izmir","en":"https://kamelya.com/en/kamelya-fiyatlari/izmir","de":"https://kamelya.com/de/kamelya-fiyatlari/izmir","fr":"https://kamelya.com/fr/kamelya-fiyatlari/izmir","it":"https://kamelya.com/it/kamelya-fiyatlari/izmir","ar":"https://kamelya.com/ar/kamelya-fiyatlari/izmir","x-default":"https://kamelya.com/kamelya-fiyatlari/izmir"}', 'Prix kamélia Izmir 2026 | Visite gratuite | Kamelya', 'Prix kamélia Izmir 2026 : modèles pour le climat égéen, visite gratuite à Bornova, plan relevé-pose clair, tarif net et calendrier d’entretien.', 'prix kamélia Izmir, prix kamélia 2026, visite gratuite, tonnelle Izmir'],
            ['ahsap-kamelya/izmir', 'fr', 'https://kamelya.com/fr/ahsap-kamelya/izmir', '{"tr":"https://kamelya.com/ahsap-kamelya/izmir","en":"https://kamelya.com/en/ahsap-kamelya/izmir","de":"https://kamelya.com/de/ahsap-kamelya/izmir","fr":"https://kamelya.com/fr/ahsap-kamelya/izmir","it":"https://kamelya.com/it/ahsap-kamelya/izmir","ar":"https://kamelya.com/ar/ahsap-kamelya/izmir","x-default":"https://kamelya.com/ahsap-kamelya/izmir"}', 'Izmir Kamélia bois 2026 | Climat Égée | Kamelya', 'Izmir kamélia bois : traitement pour le climat égéen, vernis tous les deux ans, visite gratuite, plan de pose autour de Bornova et garantie incluse.', 'kamélia bois Izmir, kamélia bois modèle, visite gratuite, tonnelle Izmir'],
            ['kamelya-fiyatlari/izmir', 'it', 'https://kamelya.com/it/kamelya-fiyatlari/izmir', '{"tr":"https://kamelya.com/kamelya-fiyatlari/izmir","en":"https://kamelya.com/en/kamelya-fiyatlari/izmir","de":"https://kamelya.com/de/kamelya-fiyatlari/izmir","fr":"https://kamelya.com/fr/kamelya-fiyatlari/izmir","it":"https://kamelya.com/it/kamelya-fiyatlari/izmir","ar":"https://kamelya.com/ar/kamelya-fiyatlari/izmir","x-default":"https://kamelya.com/kamelya-fiyatlari/izmir"}', 'Prezzi gazebo Izmir 2026 | Preventivo gratuito | Kamelya', 'Prezzi gazebo Izmir 2026: modelli per il clima egeo, sopralluogo gratuito a Bornova, piano rilievo-montaggio chiaro, prezzo netto e calendario manutenzione.', 'prezzi gazebo Izmir, prezzi gazebo 2026, sopralluogo gratuito, pensilina Izmir'],
            ['ahsap-kamelya/izmir', 'it', 'https://kamelya.com/it/ahsap-kamelya/izmir', '{"tr":"https://kamelya.com/ahsap-kamelya/izmir","en":"https://kamelya.com/en/ahsap-kamelya/izmir","de":"https://kamelya.com/de/ahsap-kamelya/izmir","fr":"https://kamelya.com/fr/ahsap-kamelya/izmir","it":"https://kamelya.com/it/ahsap-kamelya/izmir","ar":"https://kamelya.com/ar/ahsap-kamelya/izmir","x-default":"https://kamelya.com/ahsap-kamelya/izmir"}', 'Prezzi gazebo legno Izmir 2026 | Preventivo | Kamelya', 'Izmir gazebo legno: trattamento per il clima egeo, vernice ogni due anni, sopralluogo gratuito, piano posa Bornova e garanzia due anni inclusa. Elenco chiaro.', 'gazebo legno Izmir, gazebo legno modelli, sopralluogo gratuito, pensilina Izmir'],
            ['kamelya-fiyatlari/izmir', 'ar', 'https://kamelya.com/ar/kamelya-fiyatlari/izmir', '{"tr":"https://kamelya.com/kamelya-fiyatlari/izmir","en":"https://kamelya.com/en/kamelya-fiyatlari/izmir","de":"https://kamelya.com/de/kamelya-fiyatlari/izmir","fr":"https://kamelya.com/fr/kamelya-fiyatlari/izmir","it":"https://kamelya.com/it/kamelya-fiyatlari/izmir","ar":"https://kamelya.com/ar/kamelya-fiyatlari/izmir","x-default":"https://kamelya.com/kamelya-fiyatlari/izmir"}', 'كاميليا إزمير | أسعار 2026 | Kamelya', 'أسعار الكاميليا إزمير 2026: نماذج لمناخ إيجه، معاينة مجانية في بورنوفا، خطة قياس وتركيب', 'أسعار الكاميليا إزمير, أسعار كاميليا 2026, معاينة مجانية, كوش إزمير'],
            ['ahsap-kamelya/izmir', 'ar', 'https://kamelya.com/ar/ahsap-kamelya/izmir', '{"tr":"https://kamelya.com/ahsap-kamelya/izmir","en":"https://kamelya.com/en/ahsap-kamelya/izmir","de":"https://kamelya.com/de/ahsap-kamelya/izmir","fr":"https://kamelya.com/fr/ahsap-kamelya/izmir","it":"https://kamelya.com/it/ahsap-kamelya/izmir","ar":"https://kamelya.com/ar/ahsap-kamelya/izmir","x-default":"https://kamelya.com/ahsap-kamelya/izmir"}', 'كوش خشبي إزمير 2026 | إيجه | Kamelya', 'الكوش الخشبي إزمير: معالجة لمناخ إيجه، ورنيش كل عامين، معاينة مجانية، خطة تركيب قرب', 'كوش خشبي إزمير, نماذج كوش خشبي, معاينة مجانية, كوش إزمير'],
        ];
    }
};
